name: Formula
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Install tap
        run: brew tap macfanpro/tap "$GITHUB_WORKSPACE"
      - name: Build
        run: brew install --build-from-source macfanpro/tap/macfanpro
      - name: Test
        run: brew test macfanpro/tap/macfanpro
